### ISSUE TITLE
Add Django setup instructions to README.md

### ISSUE THREAD

**Issue by haroon-sheikh** [sitture/techmiya-commercials#1]
- [ ] Update readme to include setup instructions E.g. https://github.com/sitture/trade-motors

**Comment by HargovindArora** [comment]
hey @haroon-sheikh I am doing this :)

**Comment by HargovindArora** [comment]
@haroon-sheikh is this project on python 2 or 3?

**Comment by haroon-sheikh** [comment]
it was developed again python2.7 @HargovindArora

**Comment by HargovindArora** [comment]
okay @haroon-sheikh
