### ISSUE TITLE
Introduce Pep8 Linting

### ISSUE THREAD

**Issue by haroon-sheikh** [sitture/techmiya-commercials#13]

**Comment by esouthren** [comment]
I'll get on this!

**Comment by mdew192837** [comment]
How do you introduce PEP 8 lint for future commits too? @esouthren  @haroon-sheikh

**Comment by haroon-sheikh** [comment]
@mdew192837 I'd like to get a check in travis build pipeline.

**Comment by stevelle** [comment]
What would you like to do about the 941 issues currently reported?
