### ISSUE TITLE
Update Django version to latest

### ISSUE THREAD

**Issue by haroon-sheikh** [sitture/techmiya-commercials#2]
Currently the project is running on Older version of Django, I would like to upgrade to latest version.

- [x] Upgrade Django
- [x] Add `requirements.txt`

**Comment by parth-verma** [comment]
Hey i would like to fix this issue. Can you please assign it to me?

**Comment by haroon-sheikh** [comment]
Go for it @party98

**Comment by HargovindArora** [comment]
@haroon-sheikh  please see this

**Comment by rishabhnehra** [comment]
I'm on it
