### ISSUE TITLE
Dockerize the Django app

### ISSUE THREAD

**Issue by haroon-sheikh** [sitture/techmiya-commercials#3]
Create a minimal Docker container to make development easier and toward continuous delivery.

- [ ] Minimal Docker container (Maybe alpine)
- [ ] docker-compose.yml which links to mysql container, i.e. App container connects to mysql container

**Comment by alaxalves** [comment]
you want to dockerize techmiya env??

**Comment by haroon-sheikh** [comment]
Yes @alaxalves, I'd like to be able to develop/deploy using the containers.

The plan is that the same container will be built and deployed using travis.

**Comment by muhfajar** [comment]
I'm on it

**Comment by haroon-sheikh** [comment]
Thanks @muhfajar.

Docker should start 2 containers on up:
1. django
2. mysql

This may require some changes to settings.py to get credentials from env variables instead.

**Comment by muhfajar** [comment]
Should I add Nginx too?

**Comment by haroon-sheikh** [comment]
Yeah can do if you want.

**Comment by muhfajar** [comment]
I can't run Django app from your source, what Django version do you use on this project?

p.s. I see someone make pull request about upgrading Django version to 1.11

**Comment by haroon-sheikh** [comment]
@muhfajar are you able to branch off that? Or shall we get that merged in first?

**Comment by muhfajar** [comment]
I think to upgrade first and then I sync my repo with upstream, so I can setup Docker with right Django version, I mean version 1.11

**Comment by haroon-sheikh** [comment]
@muhfajar Django 1.11 changes are now in master.
