### ISSUE TITLE
CI Integration with Travis

### ISSUE THREAD

**Issue by haroon-sheikh** [sitture/techmiya-commercials#4]
Depends on https://github.com/sitture/techmiya-commercials/issues/3

- [ ] Run Tests on Travis
- [ ] Add a status badge in README.md

**Comment by aniketmaithani** [comment]
Just out of sheer curiosity. What is the Django version on which this project was initially built?

**Comment by haroon-sheikh** [comment]
It's 1.8 @aniketmaithani
